#################################################
#
# Générateur de tâches
# Fichier de configuration
#
#################################################


#################################################
# Fichiers d'entrée/sortie
#################################################

files:
  input: "tache.xls" # Avec l'extension
  output: "resultat_tache" # Sans extension, sera ajoutée automatiquement


#################################################
# Paramètres d'optimisation
#################################################

optimization:
  #################################################
  # Fonction objectif
  #################################################

  # Résoudre le problème exact, où la moyenne pondérée par le nombre d'heures enseignées est maximisée
  # Potentiellement lent à résoudre (penser à ajuster le temps limite dans la section "solver" ci-dessous)
  probleme_exact: True

  # Tenter de prendre en compte les libérations dans le problème approché (ne peut pas être activé si probleme_exact est activé). Rend la résolution potentiellement plus lente. Utile seulement si les libérés ont l'air lésés dans la solution approchée
  liberation_enabled: False


  #################################################
  # Maximisation du minimum des préférences individuelles
  #################################################

  # Optimisation lexicographique : maximiser la préférence minimale en premier, puis la moyenne pondérée des préférences
  # Attention : si `probleme_exact` est désactivé, le minimum optimal peut ne pas être le véritable minimum
  lexicographic_optimization: False
  min_lexico: 0 # Valeur minimale des préférences individuelles à atteindre. Si 0, le logiciel calculera automatiquement la valeur maximale du minimum possible des préférences individuelles et l'utilisera comme seuil. Attention : laisser 0 si `probleme_exact` est désactivé (sauf si vous savez ce que vous faites)

  # Alternative (incompatible avec lexicographic_optimization) : tenter de maximiser le minimum des préférences en même temps que la moyenne
  min_prof_enabled: False # Ne peut pas être activé si lexicographic_optimization est activé
  nbr_min_count: 50 # Nombre de fois que le minimum est compté dans la fonction objectif


  #################################################
  # Autres paramètres
  #################################################

  # Autoriser l'attribution de cours pour lesquels une préférence négative a été donnée
  allow_negative_preferences: False

  # Si un professeur a une préférence négative pour un cours attribué, s'assurer qu'il dispose également d'une préférence positive d'une valeur au moins équivalente
  enforce_positive_with_negative: False
  
  # Nombre maximum d'heures par professeur
  max_hours: 15


#################################################
# Génération de tâches alternatives
#################################################

taches_alternatives: # Paramètres pour la génération de tâches alternatives après la première optimisation

  # Nombre de solutions alternatives à générer
  nbr_taches_alternatives: 2
  # Facteur de diversité
  diversite: 1 # Nombre entier >= 1. Un facteur plus élevé produit, en théorie, des tâches alternatives plus variées. Un facteur trop élevé peut rendre la résolution difficile voir impossible


#################################################
# Paramètres du solveur
#################################################

solver:
  # Limite de temps pour chaque optimisation (en secondes)
  time_limit: 1000

  # Tolérance
  gap: 0.001

  # Log
  afficher_log: True
  sauvegarder_log: False
  fichier_log: "log.txt"