#################################################
#
# Générateur de tâches
# Fichier de configuration
#
#################################################


#################################################
# Fichiers d'entrée/sortie
#################################################

fichiers:
  entree: "tache.xls" # Avec l'extension
  sortie: "resultat_tache" # Sans extension, sera ajoutée automatiquement


#################################################
# Paramètres d'optimisation
#################################################

optimisation:
  #################################################
  # Pré-optimisations
  #################################################

  # Pré-optimisations à effectuer, et leur ordre d'exécution.
  # Les valeurs possibles sont les suivantes
  # preoptimisations: [] # Si vous ne voulez aucune pré-optimisation
  # preoptimisations: ["prof_min"] # Si vous voulez maximiser uniquement le minimum des préférences individuelles avant de maximiser la moyenne
  # preoptimisations: ["nbr_satisfaits"] # Si vous voulez maximiser uniquement le nombre de profs totalement satisfaits avant de maximiser la moyenne
  # preoptimisations: ["prof_min", "nbr_satisfaits"] # Si vous voulez d'abord maximiser le minimum des préférences individuelles, puis le nombre de profs totalement satisfaits et enfin la moyenne
  # preoptimisations: ["nbr_satisfaits", "prof_min"] # Si vous voulez d'abord maximiser le nombre de profs totalement satisfaits, puis le minimum des préférences individuelles et enfin la moyenne
  preoptimisations: []


  #################################################
  # Maximisation du minimum des préférences individuelles
  #################################################

  # Objectif : maximiser la préférence minimale en premier
  seuil_prof_min: 0.0 # Valeur minimale des préférences individuelles à atteindre. Si 0, le logiciel calculera automatiquement la valeur maximale du minimum possible des préférences individuelles et l'utilisera comme seuil.


  #################################################
  # Maximisation du nombre de profs totalement satisfaits
  #################################################

  # Objectif : maximiser le nombre de profs totalement satisfaits en premier
  seuil_nbr_satisfaits: 0 # Nombre minimum de profs totalement satisfaits à atteindre. Si 0, le logiciel calculera automatiquement le maximum possible et l'utilisera comme seuil

  #################################################
  # Autres paramètres
  #################################################

  # Ne pas autoriser l'attribution de cours pour lesquels une préférence négative a été donnée
  exclure_preferences_negatives: True

  # Nombre maximum d'heures par professeur
  nbr_heures_max: 15


#################################################
# Génération de tâches alternatives
#################################################

taches_alternatives: # Paramètres pour la génération de tâches alternatives après la première optimisation
  # Nombre de solutions alternatives à générer
  nbr_taches_alternatives: 3
  # Facteur de diversité
  diversite: 10 # Nombre entier >= 1. Nombre minimum de profs qui doivent abandonner au moins un cours qu'ils enseignaient par rapport à chacune des tâches précédemment générées. Un facteur trop élevé peut rendre la génération de tâches alternatives difficile, voire impossible


#################################################
# Log
#################################################

log:
  sauvegarder_log: False  # Si True, le log sera sauvegardé dans un fichier texte. Attention, le log précédent du même nom sera écrasé
  fichier_log: "log.txt"  # Nom du fichier dans lequel les messages sont sauvegardés. Si le fichier existe déjà, il sera écrasé