name: Build macOS Executable

on:
  workflow_dispatch:

jobs:
  build:
    # Use a macOS runner environment
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        # Python version
        python-version: '3.14'
        cache: 'pip'

    - name: Create a virtual environment
      run: |
        python -m venv venv

    - name: Install dependencies in the virtual environment
      run: |
        venv/bin/python -m pip install --upgrade pip
        # Install PyInstaller and your project's requirements
        venv/bin/pip install pyinstaller
        venv/bin/pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        # Run PyInstaller using the virtual environment's executable path
        venv/bin/pyinstaller --clean generateur_taches_onefile.spec

    - name: Copy config.yaml
      run: |
        cp src/config.yaml dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: MacOS-executable
        path: |
          dist/*
        # Upload contents of dist/ at root level